### ISSUE TITLE
UI for session participation

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#2]
Follow-up to #1 

People are now able to sign up for sessions. This only works when logged in, and currently does not provide good feedback if you're not, but assume that you are. I will make a seperate issue to improve the login flow stuff.

Currently when clicking on "signup" you get shown a blank page with the works "succesful signup". Instead we should give feedback in place.

- Change the session card rendering to indicate that you are participating
- When changing participation status, replace just the card in place

For the visual indication my current thinking is to put a checkmark on top of the circle image, and darken the image a bit.

![2024-07-26_091809](https://github.com/user-attachments/assets/53ef97f4-c01f-4190-b82c-cbde6934aa90)

**Comment by MTrost** [comment]
Pushed wip:
1. Participate post returns the card markup with checkmark
2. Participate post when already participating removes user from participants, returning card markup without a checkmark

Bug(s) to fix:
1. Somehow this disables the `expand` toggle on all other cards: Only the session card where the user clicked "Participate" can still be toggled. After a 2nd click on "Participate" everything is back to normal...
2. The `wrap-render` middleware always returns a full html document, I think because there is a default `layout-fn` that always runs. This means that the returned session card markup is not injected correctly: It's wrapped in a `main` tag. Fixing this by allowing to return partial html markup perhaps also fixes 1 🤷
3. I guess I trespassed on issue #1 a bit here in order to make it work as it should, hope that's okay. But now the button "Participate" needs a "Leave" option when you're already signed up for the session. Any naming suggestions?

I'm off for a couple of hours but will take it up again later.

**Comment by MTrost** [comment]
I fixed bug number 2, it now returns markup without `main` tag wrapping. To make it work I had to add `hx-select` to the Participate-button because it otherwise inherits the `hx-select="main"` from the `body` tag, which would select nothing in the response.

I create a different issue for bug number 1.
