### ISSUE TITLE
Create full page session route

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#3]
Currently we only show sessions as a grid, we also need a view/route for a single session, with more details.

`GET /sessions/:id`

Same stuff as on the card (title, subtitle, image, capacity guage, time/date), as well as

- Location
- Capacity / number signed up in numbers (not just visually)
- description (render as markdown!)
- List/grid of attendees (as round avatars? we'll hook this up with visibility settings later)
- Action buttons (sign up/leave/edit (we'll need some access control on that last one))

Then hook up the details button in the home page grid to go here.

**Comment by humorless** [comment]
- [x] show same stuff as on the card
- [x] show location
- [x] show capacity / number signed up in numbers if exists
- [x] show description  as markdown
- [x] show attendees as `<ol> <li> <li> </ol>`
- [x] add action buttons without actual behaviors

<img width="871" alt="截圖 2024-07-27 上午12 50 52" src="https://github.com/user-attachments/assets/eb28a0ae-6eae-4d1a-a584-7f7febf4bd35">

**Comment by humorless** [comment]
@plexus @MTrost 

When I tried to implement the `Leave` button, I found that the `Leave` backend is already implemented inside the `POST /sessions/:id/participate`. 

```
          (participants user-id)
          (do @(db/transact [[:db/cas session-eid :session/signup-count signup-cnt (dec signup-cnt)]
                             [:db/retract session-eid :session/participants user-id]])
              (session-card-response (pull-session) user))
```

Then I think there are two ways to implement.

- Design 1: 
   - We implement a `Participate` and `Leave` buttons in the UI, and I change the participate handler's behavior. 
   - The new participate handler's behavior will be idempotent no matter how many times a user press participate button. 
   
- Design 2:
  - We keep the current participate handler's implementation.
  - We implement only a `Participate` button in the UI. After the user press `Participate` and successful, that button changes to `Leave`. 
  
I am not sure if it is just a matter of taste or one design is obviously better than the other.

**Comment by MTrost** [comment]
@humorless 

I think I'd prefer a new route `/sessions/:id/leave` and we should probably extract that gets called from a `Leave`-Button. So that would be Design 1.

We have to return different things depending on where we click the respective button. 
- List view -> Only return card
- Details view -> Return details view

Coming mostly from SPAs where you just return the JSON response and let the frontend drive the view, I don't even know how best to implement this. Add a specific query parameter to the endpoint, for example
- List view -> `/sessions/:id/leave?clicked=card`
- Details view -> `/sessions/:id/leave?clicked=details`

And then branch on `clicked` (name just a draft) query param to return card view or details view?

**Comment by plexus** [comment]
This is my/our first time using htmx in anger, so I'm especially interested in discovering and thinking about these kind of patterns. I need to have a look around to see if folks have already started documenting "htmx design patterns".

This could be a valid approach: https://htmx.org/examples/update-other-content/#events

The participate/leave link doesn't return HTML, just a blank 200 OK with a header

```
HX-Trigger:session-123-updated
```

Then html elements that display information about that session can look like this

```
[:div.session-card :hx-get "/sessions/card/123" :hx-trigger "session-123-updated from:body" ,,,]
```

This would decouple read from write.

**Comment by humorless** [comment]
> This is my/our first time using htmx in anger, so I'm especially interested in discovering and thinking about these kind of patterns. I need to have a look around to see if folks have already started documenting "htmx design patterns".
> 
> This could be a valid approach: https://htmx.org/examples/update-other-content/#events
> 
> The participate/leave link doesn't return HTML, just a blank 200 OK with a header
> 
> ```
> HX-Trigger:session-123-updated
> ```
> 
> Then html elements that display information about that session can look like this
> 
> ```
> [:div.session-card :hx-get "/sessions/card/123" :hx-trigger "session-123-updated from:body" ,,,]
> ```
> 
> This would decouple read from write.

I implemented it. 

- The Network screenshot
<img width="1030" alt="截圖 2024-08-01 下午5 26 21" src="https://github.com/user-attachments/assets/ca2c31da-cdbf-4ba7-93dd-5e023e1aaab8">

- Before 
<img width="391" alt="截圖 2024-08-01 下午5 24 28" src="https://github.com/user-attachments/assets/e5981c73-ae9e-4e56-8fe8-d7bd080ef207">

- After 
<img width="393" alt="截圖 2024-08-01 下午5 24 34" src="https://github.com/user-attachments/assets/6f78e196-04fb-41b6-b47a-dd3dbb391b73">

However, when I added the required html properties to the html elements that display information about that session, I countered some bugs that I felt difficult to solve. After some struggles, I realize it is because of inheritance. 

Therefore, I added
```
:hx-disinherit "hx-target hx-select "
```
