### ISSUE TITLE
Profile functionality

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#4]
Start laying the basis of user profiles

- a page/route to see a profile
- a page/route with a form to edit a profile
- pull profile image from discord on first sign-up (but allow changing)

Much of the complexity here is around privacy controls, but let's start with getting in the basics so we have a framework to work in.

**Comment by humorless** [comment]
< Current Progress >

- showing it 
<img width="444" alt="showing-it" src="https://github.com/user-attachments/assets/5e07822f-dc24-4088-82d1-ee96add40a48">
- editing it 
<img width="457" alt="edit-profile" src="https://github.com/user-attachments/assets/d296f467-1ae4-4b7c-b3f9-336de4a70f67">
- before submit
<img width="516" alt="edit-profile-2" src="https://github.com/user-attachments/assets/3e9f479c-e07b-4048-ab34-f05e782d6510">
- after submit
<img width="491" alt="save-it" src="https://github.com/user-attachments/assets/8866279c-8e7e-4177-99ab-817fb0a0dd1d">

**Comment by humorless** [comment]
@plexus  @MTrost 

Related to the route/url of showing profile, I felt difficult to decide which design is better. 

- Design 1:  I provide url like `/proflies/{user-entity-id}`
- Design 2:  I provide url like `/proflies` 

Currently, I just go for design 2 because it is easier to integrate with Arne's navigation login. 

```
(defn a-auth [props & children]
  (if (:user props)
    (into [:a props] children)
    (into
     [:a {:hx-target "#modal"
          :hx-get (str "/login?next=" (:href props))}]
     children)))
```
If I want to use this `a-auth`, I need to calculate the correct `href` even before I login. Therefore, Design 1 does not fit well with this `a-auth`.

It seems that design 1 is more suitable when we allow people to see others' profile. Do we want to provide that kind of features?

**Comment by humorless** [comment]
show the discord avatar

<img width="374" alt="截圖 2024-08-08 下午1 59 14" src="https://github.com/user-attachments/assets/13bfee2e-bbf9-4426-887d-7a3ae0c2d976">

**Comment by humorless** [comment]
User can upload image, and the avatar can show, too.

<img width="498" alt="截圖 2024-08-08 下午6 38 53" src="https://github.com/user-attachments/assets/6db74f78-c738-4bfb-aee9-afc20f9624a0">

**Comment by humorless** [comment]
I think I finish this issue.
