### ISSUE TITLE
Improve the "create activity" form

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#7]
Current layout is very spartan, make that a bit friendlier, especially on mobile.

Instead of asking for full date/time fields for start/end, have a dropdown for the date with limited options (days before/after the event), and then time fields for start end (or a start field and a duration field).

**Comment by humorless** [comment]
- [x] Instead of asking for full date/time fields for start/end, have a dropdown for the date with limited options (days before/after the event), and then time fields for start end (or a start field and a duration field).
- [x] change the route `session/new` accordingly. 

<img width="619" alt="截圖 2024-07-27 下午12 26 49" src="https://github.com/user-attachments/assets/63da423b-dc75-4fcc-96ae-3d258b1dd608">
